language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
before_script:
  - python tests/manage.py syncdb --noinput
script: make test
notifications:
  email:
    recipients:
      - suneel0101@gmail.com
    on_success: change
    on_failure: always